### ISSUE TITLE
Collection lacks ToEntry()

### ISSUE THREAD

**Issue by ollystephens** [contentful-labs/contentful-go#12]
Collection has all the other type assertions, but lacks ToEntry(). Inlining the equivalent code achieves the desired effect, so I assume this is just a simple omission.

**Comment by tolgaakyuz** [comment]
@ollystephens sorry for not being able to reply sooner. you're right, I'll add the type assertion as soon as possible. Cheers.

**Comment by hooloovooo** [comment]
#14 fixes this

**Comment by ddevcap** [comment]
This issue can be closed ;)
