### ISSUE TITLE
Example to retrieve the content of a specified content-type

### ISSUE THREAD

**Issue by p4tin** [contentful-labs/contentful-go#36]
Could someone post an example of retreiving the actual data from a content-type. (i.e.: I have a content-type of 'product' and I want to get a complete list of the content that I have created for that content-type.  I am looking at using this SDK not the API directly.

Thanks!

**Comment by atecce** [comment]
`/entries?content_type=<example>`

**Comment by p4tin** [comment]
I meant using this SDK not the API directly.

**Comment by atecce** [comment]
just use `contentful.Get` paul. check `./global_promo_container.go` for an example

**Comment by ItsLeeOwen** [comment]
For anyone else arriving here a bit puzzled:

```go
var err error
cda := contentful.NewCDA("your-cma-token")

space, err := cda.Spaces.Get("your-space-id")
if err != nil {
	log.Fatal(err)
}

collection := cda.Entries.List(space.Sys.ID)

collection.Query = *collection.
	ContentType("your-content-type").
	Order("sys.createdAt", true).
	Limit(25)

collection, err = collection.Next()
if err != nil {
	log.Fatal(err)
}

for _, entry := range collection.ToEntry() {
	spew.Dump("entry:", entry)
}
```
